In [66]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 
# Importing the database
dataset = pd.read_csv('dataset/Churn_Modelling.csv')

In [67]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [68]:
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [69]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [70]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder() 
X[:,1] = labelencoder_X_1.fit_transform(X[:,1]) 
labelencoder_X_2 = LabelEncoder() 
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [71]:
from sklearn.compose import ColumnTransformer

# Assuming X is a DataFrame with columns to be one-hot encoded
column_transformer = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(), [1])  # Replace [1] with the column indices you want to encode
    ],
    remainder='passthrough'
)

X = column_transformer.fit_transform(X)
X.shape

(10000, 12)

In [72]:
#Splitting the dataset into the Training set and the Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

In [73]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

In [74]:
# Importing the Keras libraries and packages 
import keras 
from keras.models import Sequential 
from keras.layers import Dense

In [75]:
classifier = keras.Sequential([
    keras.layers.Dense(6,kernel_initializer='uniform',activation='relu',input_dim=12),
    keras.layers.Dense(6,kernel_initializer='uniform',activation='relu'),
    keras.layers.Dense(1,kernel_initializer='uniform',activation='sigmoid')
])

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [76]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50


800/800 [==============================] - 2s 1ms/step - loss: 0.4936 - accuracy: 0.7955
Epoch 2/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4256 - accuracy: 0.7968
Epoch 3/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4184 - accuracy: 0.7968
Epoch 4/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4135 - accuracy: 0.8234
Epoch 5/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4103 - accuracy: 0.8329
Epoch 6/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4084 - accuracy: 0.8341
Epoch 7/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4064 - accuracy: 0.8354
Epoch 8/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4047 - accuracy: 0.8351
Epoch 9/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4033 - accuracy: 0.8381
Epoch 10/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4020 - accuracy: 0.8378
Epoch 11/5

In [77]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 1ms/step


In [78]:
new_prediction = classifier.predict(sc.transform
(np.array([[0.0, 0, 500, 1, 40, 3, 50000, 2, 1, 1, 40000]])))
new_prediction = (new_prediction > 0.5)

ValueError: X has 11 features, but StandardScaler is expecting 12 features as input.

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print (cm)